rgname11 = "Terraform-rg11"
rgname22 = "Terraform-rg22"
location = "East US 2"
storageacc1 = "milestonesssss11"
storageacc2 = "milestonesssss22"
tier = "Standard"
replication = "LRS"
nsg1 = "terraform-ng11"